### ISSUE TITLE
Cannot import sinon-chrome with webpack

### ISSUE THREAD

**Issue by sk-** [acvetkov/sinon-chrome#11]
When I try to require the new version `1.0.0` with webpack I get the following error.

```
TypeError: 'undefined' is not an object (evaluating 'modules[moduleId].call')
```

**Comment by acvetkov** [comment]
Hi.

It's legendary problem =).
Check out this issue in webpack repo
https://github.com/webpack/webpack/issues/304

This problem is related with incorrect sinon exports module interface, you should load sinon "manually" to solve it.

**Comment by sk-** [comment]
I'm not sure that is the problem. I'm using version 2.0 of sinon from
github and I did not have any troubles when requiring the previous version
of sinon chrome with webpack.

**Comment by acvetkov** [comment]
@sk-, Because we have bundled sinon-chrome by webpack since 1.0 version.

In version < 1.0, we have not build with resolving dependencies, only js files concatination.

I think, I can fix our webpack config to solve this problem.

But you should know, you can do it in your project webpack config. Just fix loader for sinon module.

**Comment by acvetkov** [comment]
@sk- Can you change your webpack config?
Add rules

```js

var path = require('path');

// ...

resolve: {
   alias: {
      sinon: path.resolve(__dirname, 'node_modules/sinon/pkg/sinon.js') // require dist version instead
   }
},
module: {
   noParse: [
      /node_modules\/sinon/ // ignore sinon module
   ]   
}
```

You should install `sinon` before

**Comment by michalczaplinski** [comment]
@acvetkov 
Your config almost worked for me - I had to make 2 modifications:

1. Use the unbundled version of `sinon that is inside `node_modules/sinon/lib` instead of `node_modules/sinon/pkg`
2. Add the `$` to the `noParse` rule. Otherwise it would also eagerly cover the `sinon-chrome` package itself!

```
var path = require('path');

// ...

resolve: {
   alias: {
      sinon: path.resolve(__dirname, 'node_modules/sinon/lib/sinon.js') // require dist version instead
   }
},
module: {
   noParse: [
      /node_modules\/sinon$/ // ignore sinon module
   ]   
}
```
